[versions]
timber = "4.7.1"
appCompat = "1.3.0"
material = "1.3.0"
constraintLayout = "1.1.3"
jUnit = "4.11"
kotlin = "1.6.10"
gradlePlugin = "7.1.2"

[libraries]

appCompat = {module = "androidx.appcompat:appcompat",version.ref = "appCompat"}
timber = {module = "com.jakewharton.timber:timber",version.ref = "timber"}
kotlin = {module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7",version.ref = "kotlin"}
materialDesign = {module = "com.google.android.material:material",version.ref = "material"}
constraintLayout = {module = "androidx.constraintlayout:constraintlayout",version.ref = "constraintLayout"}
junit = {module = "junit:junit",version.ref = "jUnit"}
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-tools-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugin" }